{{- define "my-istio-library.gateway" -}}
{{- with .Values.gateway }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  selector:
    {{- toYaml .selector | nindent 4 }}
  servers:
  - port:
      number: {{ .httpPort }}
      name: http
      protocol: HTTP
    hosts:
    - {{ quote .hosts | join ", " }}
{{- if .httpsPort }}
  - port:
      number: {{ .httpsPort }}
      name: https
      protocol: HTTPS
    hosts:
    - {{ quote .hosts | join ", " }}
    tls:
      mode: {{ .tlsMode }}
      {{- if eq .tlsMode "SIMPLE" }}
      credentialName: {{ .tlsSecretName }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}