{{- define "my-istio-library.virtualservice" -}}
{{- with .Values.virtualService }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  hosts:
  - {{ quote .hosts | join ", " }}
  gateways:
  - {{ .name }} # Assuming gateway name is the same as virtualservice name for simplicity.  Adjust if needed.
  http:
  - route:
    - destination:
        host: {{ .serviceName }}
        port:
          number: {{ .servicePort }}
{{- end }}
{{- end }}